language: java
sudo: false
script: mvn ${JACOCO} test
matrix:
 include:
   # Covers Java 7, Open JDK, and code coverage
   - jdk: openjdk7
     env: JACOCO=-Pjacoco
   # Covers Java 8, Oracle JDK
   - jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
git:
  depth: 10
after_success: bash <(curl -s https://codecov.io/bash)
env:
  global:
   # COVERITY_SCAN:
   - secure: "HmfK5Ya1l1/hWFk+RV5lwlrWAlv3FwyOFV1689JPtK9OBZAuDGmj0uskmLRWI7X6MdwHSpP93P5pADE1YbbqX2pZmhysBiLsGh8rmI+eTm/Q9h708qyRk3T2Yie49rfk5xlo1IN41dDt+3XZ0bEC7VEXNoCAyn9YMpZ/wOJiP/s="
addons:
  coverity_scan:
    project:
      name: "zxing/zxing"
      description: "Build submitted via Travis CI"
    notification_email: srowen@gmail.com
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile test-compile"
    branch_pattern: coverity_scan