language: java
sudo: false
install: mvn -T 2 -Ptravis -DskipTests=true -B -V install
script:
  - mvn -T 2 -Ptravis ${JACOCO} test
  - find $HOME/.m2/repository/com/google/zxing -path "*SNAPSHOT/*" -delete
  - find $HOME/.m2/repository/com/google/zxing -name "*SNAPSHOT" -type d -delete
matrix:
 include:
   # Covers Java 7, Open JDK, and code coverage
   - jdk: openjdk7
     env: JACOCO=-Pjacoco
   # Covers Java 8, Oracle JDK, Android apps
   - jdk: oraclejdk8
     env: ANDROID_HOME=$HOME/android-sdk-linux
     before_install: if [ ! -d $HOME/android-sdk-linux/tools ]; then curl -s https://storage.googleapis.com/zxing-build/android-sdk-linux.tar.bz2 | bunzip2 | tar xf - -C $HOME; else ls -l $HOME/android-sdk-linux; fi
cache:
  directories:
    - $HOME/.m2
    - $HOME/android-sdk-linux
git:
  depth: 10
after_success: if [ -n "$JACOCO" ]; then bash <(curl -s https://codecov.io/bash); fi